const version = `b1.0.4.0`;
const banner = `<img src = "webassets/banner.png" class = "banner" alt = "banner wasn't able to render :&lpar;" /`;
function list2(functionInput2){
    let temp = [""];
    for(var cur in functionInput2){
        let temp2 = typeof(functionInput2[cur])
        if (temp2 == "string"){
            temp.push(`• ${functionInput2[cur].toString()}<br>`);
        } else if (temp2 == "object"){
            if (functionInput2[cur].length==1){
                temp.push(`&emsp;&emsp;• ${functionInput2[cur][0].toString()}<br>`);
            } else if (functionInput2[cur].length == 2){
                temp.push(`${"&emsp;".repeat(functionInput2[cur][1])}• ${functionInput2[cur][0].toString()}<br>`);
            };
        };
    };
    temp.slice(1);
    return temp.join("");
};
const changelog_content = `
    ${banner}<br><br>
    <h1>Local Oaf's 4&times;4 - Version ${version}</h1>
    <details><summary><h2>b1.0.0.0 (May 11<sup>th</sup>, 2025)</h2></summary><p>
        ${list2([
            "Added/Modified files:",
            ["$textures/block/acacia_door_bottom.png"],
            ["$textures/block/acacia_door_top.png"],
            ["$textures/block/acacia_leaves.png"],
            ["$textures/block/acacia_log.png"],
            ["$textures/block/acacia_log_top.png"],
            ["$textures/block/acacia_planks.png"],
            ["$textures/block/acacia_sapling.png"],
            ["$textures/block/acacia_trapdoor.png"],
            ["$textures/block/activator_rail.png"],
            ["$textures/block/activator_rail_on.png"],
            ["$textures/block/allium.png"],
            ["$textures/block/amethyst_block.png"],
            ["$textures/block/amethyst_cluster.png"],
            ["$textures/block/ancient_debris_side.png"],
            ["$textures/block/ancient_debris_top.png"],
            ["$textures/block/andesite.png"],
            ["$textures/block/anvil.png"],
            ["$textures/block/anvil_top.png"],
            ["$textures/block/attached_melon_stem.png"],
            ["$textures/block/attached_pumpkin_stem.png"],
            ["$textures/block/azalea_leaves.png"],
            ["$textures/block/azalea_plant.png"],
            ["$textures/block/azalea_side.png"],
            ["$textures/block/azalea_top.png"],
            ["$textures/block/azure_bluet.png"],
            ["$textures/block/bamboo_block.png"],
            ["$textures/block/bamboo_block_top.png"],
            ["$textures/block/bamboo_door_bottom.png"],
            ["$textures/block/bamboo_door_top.png"],
            ["$textures/block/bamboo_fence_gate_particle.png"],
            ["$textures/block/bamboo_fence_particle.png"],
            ["$textures/block/bamboo_large_leaves.png"],
            ["$textures/block/bamboo_mosaic.png"],
            ["$textures/block/bamboo_planks.png"],
            ["$textures/block/bamboo_singleleaf.png"],
            ["$textures/block/bamboo_small_leaves.png"],
            ["$textures/block/bamboo_stage0.png"],
            ["$textures/block/bamboo_stalk.png"],
            ["$textures/block/bamboo_trapdoor.png"],
            ["%webassets/core.js"],
            ["%webassets/guide.css"],
            ["%webassets/mc.ttf"],
            ["%_changelog.png"],
            ["%_credits.png"],
            ["%_guide.png"],
            ["%pack.mcmeta"],
            ["%pack.png"]
        ])}
    </p></details><br><details><summary><h2>b1.0.1.0 (May 12<sup>th</sup>, 2025)</h2></summary><p>
        ${list2([
            "Added/Modified files:",
            ["$textures/block/barrel_bottom.png"],
            ["$textures/block/barrel_side.png"],
            ["$textures/block/barrel_top.png"],
            ["$textures/block/barrel_top_open.png"],
            ["$textures/block/basalt_side.png"],
            ["$textures/block/basalt_top.png"],
            ["$textures/block/beacon.png"],
            ["$textures/block/bedrock.png"],
            ["$textures/block/bee_nest_bottom.png"],
            ["$textures/block/bee_nest_front.png"],
            ["$textures/block/bee_nest_front_honey.png"],
            ["$textures/block/bee_nest_side.png"],
            ["$textures/block/bee_nest_top.png"],
            ["$textures/block/beehive_end.png"],
            ["$textures/block/beehive_front.png"],
            ["$textures/block/beehive_front_honey.png"],
            ["$textures/block/beehive_side.png"],
            ["$textures/block/beetroots_stage0.png"],
            ["$textures/block/beetroots_stage1.png"],
            ["$textures/block/beetroots_stage2.png"],
            ["$textures/block/beetroots_stage3.png"],
            ["$textures/block/big_dripleaf_side.png"],
            ["$textures/block/big_dripleaf_stem.png"],
            ["$textures/block/big_dripleaf_tip.png"],
            ["$textures/block/big_dripleaf_top.png"],
            ["$textures/block/birch_door_bottom.png"],
            ["$textures/block/birch_door_top.png"],
            ["$textures/block/birch_leaves.png"],
            ["$textures/block/birch_log.png"],
            ["$textures/block/birch_log_top.png"],
            ["$textures/block/birch_planks.png"],
            ["$textures/block/birch_sapling.png"],
            ["$textures/block/birch_trapdoor.png"],
            ["$textures/block/black_concrete.png"],
            ["$textures/block/black_concrete_powder.png"],
            ["$textures/block/black_glazed_terracotta.png"],
            ["$textures/block/black_shulker_box.png"],
            ["$textures/block/black_stained_glass.png"],
            ["$textures/block/black_stained_glass_pane_top.png"],
            ["$textures/block/black_terracotta.png"],
            ["$textures/block/black_wool.png"],
            ["$textures/block/blackstone.png"],
            ["$textures/block/blackstone_top.png"],
            ["$textures/block/blast_furnace_front.png"],
            ["$textures/block/blast_furnace_front_on.png"],
            ["$textures/block/blast_furnace_front_on.png.mcmeta"],
            ["$textures/block/blast_furnace_side.png"],
            ["$textures/block/blast_furnace_top.png"],
            ["$textures/block/blue_concrete.png"],
            ["$textures/block/blue_concrete_powder.png"],
            ["$textures/block/blue_glazed_terracotta.png"],
            ["$textures/block/blue_ice.png"],
            ["$textures/block/blue_orchid.png"],
            ["$textures/block/blue_shulker_box.png"],
            ["$textures/block/blue_stained_glass.png"],
            ["$textures/block/blue_stained_glass_pane_top.png"],
            ["$textures/block/blue_terracotta.png"],
            ["$textures/block/blue_wool.png"],
            ["$textures/block/bone_block_side.png"],
            ["$textures/block/bone_block_top.png"],
            ["$textures/block/bookshelf.png"],
            ["$textures/block/brain_coral.png"],
            ["$textures/block/brain_coral_block.png"],
            ["$textures/block/brain_coral_fan.png"],
            ["$textures/block/brewing_stand.png"],
            ["$textures/block/brewing_stand_base.png"],
            ["$textures/block/bricks.png"],
            ["$textures/block/brown_concrete.png"],
            ["$textures/block/brown_concrete_powder.png"],
            ["$textures/block/brown_glazed_terracotta.png"],
            ["$textures/block/brown_mushroom.png"],
            ["$textures/block/brown_mushroom_block.png"],
            ["$textures/block/brown_shulker_box.png"],
            ["$textures/block/brown_stained_glass.png"],
            ["$textures/block/brown_stained_glass_pane_top.png"],
            ["$textures/block/brown_terracotta.png"],
            ["$textures/block/brown_wool.png"],
            ["$textures/block/bubble_coral.png"],
            ["$textures/block/bubble_coral_block.png"],
            ["$textures/block/bubble_coral_fan.png"],
            ["$textures/block/budding_amethyst.png"],
            ["$textures/block/bush.png"],
            ["$textures/block/cactus_bottom.png"],
            ["$textures/block/cactus_flower.png"],
            ["$textures/block/cactus_side.png"],
            ["$textures/block/cactus_top.png"],
            ["$textures/block/cake_bottom.png"],
            ["$textures/block/cake_side.png"],
            ["$textures/block/cake_top.png"],
            ["$textures/block/calcite.png"],
            ["$textures/block/calibrated_sculk_sensor_amethyst.png"],
            ["$textures/block/calibrated_sculk_sensor_input_side.png"],
            ["$textures/block/calibrated_sculk_sensor_top.png"],
            ["$textures/block/campfire_fire.png"],
            ["$textures/block/campfire_fire.png.mcmeta"],
            ["$textures/block/campfire_log.png"],
            ["$textures/block/campfire_log_lit.png"],
            ["$textures/block/campfire_log_lit.png.mcmeta"],
            ["$textures/block/carrots_stage0.png"],
            ["$textures/block/carrots_stage1.png"],
            ["$textures/block/carrots_stage2.png"],
            ["$textures/block/carrots_stage3.png"],
            ["$textures/block/cartography_table_side1.png"],
            ["$textures/block/cartography_table_side2.png"],
            ["$textures/block/cartography_table_side3.png"],
            ["$textures/block/cartography_table_top.png"],
            ["$textures/gui/title/edition.png"],
            ["$textures/gui/title/edition.png.mcmeta"],
            ["$textures/gui/title/minceraft.png"],
            ["$textures/gui/title/minceraft.png.mcmeta"],
            ["$textures/gui/title/minecraft.png"],
            ["$textures/gui/title/minecraft.png.mcmeta"],
            ["$textures/gui/title/mojangstudios.png"],
            ["$textures/gui/title/mojangstudios.png.mcmeta"],
            ["$textures/gui/title/realms.png"],
            ["$textures/gui/title/realms.png.mcmeta"],
            ["$textures/painting/alban.png"],
            ["$textures/painting/aztec.png"],
            ["$textures/painting/aztec2.png"],
            ["$textures/painting/back.png"],
            ["$textures/painting/backyard.png"],
            ["$textures/painting/baroque.png"],
            ["$textures/painting/bomb.png"],
            ["$textures/painting/bouquet.png"],
            ["$textures/painting/burning_skull.png"],
            ["$textures/painting/bust.png"],
            ["$textures/painting/cavebird.png"],
            ["$textures/painting/changing.png"],
            ["$textures/painting/cotan.png"],
            ["$textures/painting/courbet.png"],
            ["$textures/painting/creebet.png"],
            ["$textures/painting/donkey_kong.png"],
            ["$textures/painting/earth.png"],
            ["$textures/painting/endboss.png"],
            ["$textures/painting/fern.png"],
            ["$textures/painting/fighters.png"],
            ["$textures/painting/finding.png"],
            ["$textures/painting/fire.png"],
            ["$textures/painting/graham.png"],
            ["$textures/painting/humble.png"],
            ["$textures/painting/kebab.png"],
            ["$textures/painting/kz.png"],
            ["$textures/painting/lowmist.png"],
            ["$textures/painting/match.png"],
            ["$textures/painting/meditative.png"],
            ["$textures/painting/orb.png"],
            ["$textures/painting/owlemons.png"],
            ["$textures/painting/passage.png"],
            ["$textures/painting/pigscene.png"],
            ["$textures/painting/plant.png"],
            ["$textures/painting/pointer.png"],
            ["$textures/painting/pond.png"],
            ["$textures/painting/pool.png"],
            ["$textures/painting/prairie_ride.png"],
            ["$textures/painting/sea.png"],
            ["$textures/painting/skeleton.png"],
            ["$textures/painting/skull_and_roses.png"],
            ["$textures/painting/stage.png"],
            ["$textures/painting/sunflowers.png"],
            ["$textures/painting/sunset.png"],
            ["$textures/painting/tides.png"],
            ["$textures/painting/unpacked.png"],
            ["$textures/painting/void.png"],
            ["$textures/painting/wanderer.png"],
            ["$textures/painting/wasteland.png"],
            ["$textures/painting/water.png"],
            ["$textures/painting/wind.png"],
            ["$textures/painting/wither.png"]
        ])}
    </p></details><br><details><summary><h2>b1.0.2.0 (May 16<sup>th</sup>, 2025)</h2></summary><p>
        ${list2([
            "Added/Modified files:",
            ["$models/block/chain.json"],
            ["$models/block/short_grass.json"], // backwards file ref
            ["$textures/block/carved_pumpkin.png"],
            ["$textures/block/cauldron_bottom.png"],
            ["$textures/block/cauldron_inner.png"],
            ["$textures/block/cauldron_side.png"],
            ["$textures/block/cauldron_top.png"],
            ["$textures/block/cave_vines.png"],
            ["$textures/block/cave_vines_lit.png"],
            ["$textures/block/cave_vines_plant.png"],
            ["$textures/block/cave_vines_plant_lit.png"],
            ["$textures/block/chain.png"],
            ["$textures/block/chain_command_block_back.png"],
            ["$textures/block/chain_command_block_back.png.mcmeta"],
            ["$textures/block/chain_command_block_conditional.png"],
            ["$textures/block/chain_command_block_conditional.png.mcmeta"],
            ["$textures/block/chain_command_block_front.png"],
            ["$textures/block/chain_command_block_front.png.mcmeta"],
            ["$textures/block/chain_command_block_side.png"],
            ["$textures/block/chain_command_block_side.png.mcmeta"],
            ["$textures/block/cherry_door_bottom.png"],
            ["$textures/block/cherry_door_top.png"],
            ["$textures/block/cherry_leaves.png"],
            ["$textures/block/cherry_log.png"],
            ["$textures/block/cherry_log_top.png"],
            ["$textures/block/cherry_planks.png"],
            ["$textures/block/cherry_sapling.png"],
            ["$textures/block/cherry_trapdoor.png"],
            ["$textures/block/chipped_anvil_top.png"],
            ["$textures/block/chiseled_bookshelf_empty.png"],
            ["$textures/block/chiseled_bookshelf_occupied.png"],
            ["$textures/block/chiseled_bookshelf_side.png"],
            ["$textures/block/chiseled_bookshelf_top.png"],
            ["$textures/block/chiseled_copper.png"],
            ["$textures/block/chiseled_deepslate.png"],
            ["$textures/block/chiseled_nether_bricks.png"],
            ["$textures/block/chiseled_polished_blackstone.png"],
            ["$textures/block/chiseled_quartz_block.png"],
            ["$textures/block/chiseled_quartz_block_top.png"],
            ["$textures/block/chiseled_red_sandstone.png"],
            ["$textures/block/chiseled_resin_bricks.png"],
            ["$textures/block/chiseled_sandstone.png"],
            ["$textures/block/chiseled_stone_bricks.png"],
            ["$textures/block/chiseled_tuff.png"],
            ["$textures/block/chiseled_tuff_bricks.png"],
            ["$textures/block/chiseled_tuff_bricks_top.png"],
            ["$textures/block/chiseled_tuff_top.png"],
            ["$textures/block/chorus_flower.png"],
            ["$textures/block/chorus_flower_dead.png"],
            ["$textures/block/chorus_plant.png"],
            ["$textures/block/clay.png"],
            ["$textures/block/closed_eyeblossom.png"],
            ["$textures/block/coal_block.png"],
            ["$textures/block/coal_ore.png"],
            ["$textures/block/coarse_dirt.png"],
            ["$textures/block/cobbled_deepslate.png"],
            ["$textures/block/cobblestone.png"],
            ["$textures/block/cobweb.png"],
            ["$textures/block/command_block_back.png"],
            ["$textures/block/command_block_back.png.mcmeta"],
            ["$textures/block/command_block_conditional.png"],
            ["$textures/block/command_block_conditional.png.mcmeta"],
            ["$textures/block/command_block_front.png"],
            ["$textures/block/command_block_front.png.mcmeta"],
            ["$textures/block/command_block_side.png"],
            ["$textures/block/command_block_side.png.mcmeta"],
            ["$textures/entity/zombie_pigman.png"],
            ["$textures/entity/player/wide/alex.png"],
            ["$textures/entity/player/wide/ari.png"],
            ["$textures/entity/player/wide/efe.png"],
            ["$textures/entity/player/wide/kai.png"],
            ["$textures/entity/player/wide/makena.png"],
            ["$textures/entity/player/wide/noor.png"],
            ["$textures/entity/player/wide/steve.png"],
            ["$textures/entity/player/wide/sunny.png"],
            ["$textures/entity/player/wide/zuri.png"],
            ["$textures/entity/zombie/drowned.png"],
            ["$textures/entity/zombie/drowned_outer_layer.png"],
            ["$textures/entity/zombie/husk.png"],
            ["$textures/entity/zombie/zombie.png"],
            ["$textures/environment/end_sky.png"],
            ["$textures/environment/moon_phases.png"],
            ["$textures/environment/rain.png"],
            ["$textures/environment/snow.png"],
            ["$textures/environment/sun.png"],
            ["$textures/gui/presets/isles.png"],
            ["$textures/gui/realms/adventure.png"],
            ["$textures/gui/realms/empty_frame.png"],
            ["$textures/gui/realms/experience.png"],
            ["$textures/gui/realms/inspiration.png"],
            ["$textures/gui/realms/new_world.png"],
            ["$textures/gui/realms/survival_spawn.png"],
            ["$textures/gui/realms/upload.png"],
            ["$textures/misc/credits_vignette.png"],
            ["$textures/misc/credits_vignette.png.mcmeta"],
            ["$textures/misc/enchanted_glint_entity.png"],
            ["$textures/misc/enchanted_glint_item.png"],
            ["$textures/misc/enchanted_glint_item.png.mcmeta"],
            ["$textures/misc/forcefield.png"], // world border
            ["$textures/misc/nausea.png"],
            ["$textures/misc/nausea.png.mcmeta"],
            ["$textures/misc/powder_snow_outline.png"],
            ["$textures/misc/pumpkinblur.png"],
            ["$textures/misc/pumpkinblur.png.mcmeta"],
            ["$textures/misc/shadow.png"],
            ["$textures/misc/shadow.png.mcmeta"],
            ["$textures/misc/spyglass_scope.png"],
            ["$textures/misc/underwater.png"],
            ["$textures/misc/unknown_pack.png"],
            ["$textures/misc/unknown_server.png"],
            ["$textures/misc/vignette.png"],
            ["$textures/misc/vignette.png.mcmeta"],
        ])}
    </p></details><br><details><summary><h2>b1.0.3.0 (May 16<sup>th</sup>, 2025)</h2></summary><p>
        ${list2([
            "Added/Modified files:",
            ["$blockstates/composter.json"],
            ["$models/block/cactus.json"],
            ["$models/block/composter.json"],
            ["$models/block/composter_contents_ready.json"],
            ["$models/block/composter_contents1.json"],
            ["$models/block/composter_contents3.json"],
            ["$models/block/composter_contents5.json"],
            ["$models/block/composter_contents7.json"],
            ["$textures/block/comparator.png"],
            ["$textures/block/comparator_on.png"],
            ["$textures/block/composter_bottom.png"],
            ["$textures/block/composter_compost.png"],
            ["$textures/block/composter_ready.png"],
            ["$textures/block/composter_side.png"],
            ["$textures/block/composter_top.png"],
            ["$textures/block/conduit.png"],
            ["$textures/block/copper_block.png"],
            ["$textures/block/copper_bulb.png"],
            ["$textures/block/copper_bulb_lit.png"],
            ["$textures/block/copper_bulb_lit_powered.png"],
            ["$textures/block/copper_bulb_powered.png"],
            ["$textures/block/copper_door_bottom.png"],
            ["$textures/block/copper_door_top.png"],
            ["$textures/block/copper_grate.png"],
            ["$textures/block/copper_ore.png"],
            ["$textures/block/copper_trapdoor.png"],
            ["$textures/block/cornflower.png"],
            ["$textures/block/cracked_deepslate_bricks.png"],
            ["$textures/block/cracked_deepslate_tiles.png"],
            ["$textures/block/cracked_nether_bricks.png"],
            ["$textures/block/cracked_polished_blackstone_bricks.png"],
            ["$textures/block/cracked_stone_bricks.png"],
            ["$textures/block/crafter_bottom.png"],
            ["$textures/block/crafter_east.png"],
            ["$textures/block/crafter_east_crafting.png"],
            ["$textures/block/crafter_east_triggered.png"],
            ["$textures/block/crafter_north.png"],
            ["$textures/block/crafter_north_crafting.png"],
            ["$textures/block/crafter_south.png"],
            ["$textures/block/crafter_south_triggered.png"],
            ["$textures/block/crafter_top.png"],
            ["$textures/block/crafter_top_crafting.png"],
            ["$textures/block/crafter_top_triggered.png"],
            ["$textures/block/crafter_west.png"],
            ["$textures/block/crafter_west_crafting.png"],
            ["$textures/block/crafter_west_triggered.png"],
            ["$textures/block/crafting_table_front.png"],
            ["$textures/block/crafting_table_side.png"],
            ["$textures/block/crafting_table_top.png"],
            ["$textures/block/creaking_heart.png"],
            ["$textures/block/creaking_heart_active.png"],
            ["$textures/block/creaking_heart_dormant.png"],
            ["$textures/block/creaking_heart_top.png"],
            ["$textures/block/creaking_heart_top_active.png"],
            ["$textures/block/creaking_heart_top_dormant.png"],
            ["$textures/block/crimson_door_bottom.png"],
            ["$textures/block/crimson_door_top.png"],
            ["$textures/block/crimson_fungus.png"],
            ["$textures/block/crimson_nylium.png"],
            ["$textures/block/crimson_nylium_side.png"],
            ["$textures/block/crimson_planks.png"],
            ["$textures/block/crimson_roots.png"],
            ["$textures/block/crimson_roots_pot.png"],
            ["$textures/block/crimson_stem.png"],
            ["$textures/block/crimson_stem.png.mcmeta"],
            ["$textures/block/crimson_stem_top.png"],
            ["$textures/block/crimson_trapdoor.png"],
            ["$textures/block/crying_obsidian.png"],
            ["$textures/block/cut_copper.png"],
            ["$textures/block/cut_red_sandstone.png"],
            ["$textures/block/cut_sandstone.png"]
        ])}
    </p></details><br><details><summary><h2>b1.0.4.0 (May 17<sup>th</sup>, 2025)</h2></summary><p>
        ${list2([
            "Added/Modified files:",
            ["$models/block/cactus.json"],
            ["$models/block/cake.json"],
            ["$models/block/cake_slice1.json"],
            ["$models/block/cake_slice2.json"],
            ["$models/block/cake_slice3.json"],
            ["$models/block/cake_slice4.json"],
            ["$models/block/cake_slice5.json"],
            ["$models/block/cake_slice6.json"],
            ["$models/block/campfire_off.json"],
            ["$models/block/crop.json"],
            ["$models/block/dirt_path.json"],
            ["$models/block/dragon_egg.json"],
            ["$models/block/end_portal_frame.json"],
            ["$models/block/end_portal_frame_filled.json"],
            ["$models/block/flower_pot.json"],
            ["$models/block/grass_path.json"],
            ["$models/block/potted_azalea_bush.json"],
            ["$models/block/potted_flowering_azalea_bush.json"],
            ["$models/block/template_campfire.json"],
            ["$models/block/template_daylight_detector.json"],
            ["$models/block/template_farmland.json"],
            ["$models/block/tinted_flower_pot_cross.json"],
            ["$models/item/generated.json"],
            ["$models/item/short_grass.json"],
            ["$models/item/_oaf/generated_render.json"],
            ["$textures/block/cyan_concrete.png"],
            ["$textures/block/cyan_concrete_powder.png"],
            ["$textures/block/cyan_glazed_terracotta.png"],
            ["$textures/block/cyan_shulker_box.png"],
            ["$textures/block/cyan_stained_glass.png"],
            ["$textures/block/cyan_stained_glass_pane_top.png"],
            ["$textures/block/cyan_terracotta.png"],
            ["$textures/block/cyan_wool.png"],
            ["$textures/block/damaged_anvil_top.png"],
            ["$textures/block/dandelion.png"],
            ["$textures/block/dark_oak_door_bottom.png"],
            ["$textures/block/dark_oak_door_top.png"],
            ["$textures/block/dark_oak_leaves.png"],
            ["$textures/block/dark_oak_log.png"],
            ["$textures/block/dark_oak_log_top.png"],
            ["$textures/block/dark_oak_planks.png"],
            ["$textures/block/dark_oak_sapling.png"],
            ["$textures/block/dark_oak_trapdoor.png"],
            ["$textures/block/dark_prismarine.png"],
            ["$textures/block/daylight_detector_inverted_top.png"],
            ["$textures/block/daylight_detector_side.png"],
            ["$textures/block/daylight_detector_top.png"],
            ["$textures/block/dead_brain_coral.png"],
            ["$textures/block/dead_brain_coral_block.png"],
            ["$textures/block/dead_brain_coral_fan.png"],
            ["$textures/block/dead_bubble_coral.png"],
            ["$textures/block/dead_bubble_coral_block.png"],
            ["$textures/block/dead_bubble_coral_fan.png"],
            ["$textures/block/dead_bush.png"],
            ["$textures/block/dead_fire_coral.png"],
            ["$textures/block/dead_fire_coral_block.png"],
            ["$textures/block/dead_fire_coral_fan.png"],
            ["$textures/block/dead_horn_coral.png"],
            ["$textures/block/dead_horn_coral_block.png"],
            ["$textures/block/dead_horn_coral_fan.png"],
            ["$textures/block/dead_tube_coral.png"],
            ["$textures/block/dead_tube_coral_block.png"],
            ["$textures/block/dead_tube_coral_fan.png"],
            ["$textures/block/debug.png"],
            ["$textures/block/debug2.png"],
            ["$textures/block/deepslate.png"],
            ["$textures/block/deepslate_bricks.png"],
            ["$textures/block/deepslate_coal_ore.png"],
            ["$textures/block/deepslate_copper_ore.png"],
            ["$textures/block/deepslate_diamond_ore.png"],
            ["$textures/block/deepslate_emerald_ore.png"],
            ["$textures/block/deepslate_gold_ore.png"],
            ["$textures/block/deepslate_iron_ore.png"],
            ["$textures/block/deepslate_lapis_ore.png"],
            ["$textures/block/deepslate_redstone_ore.png"],
            ["$textures/block/deepslate_tiles.png"],
            ["$textures/block/deepslate_top.png"],
            ["$textures/block/destroy_stage_0.png"],
            ["$textures/block/destroy_stage_1.png"],
            ["$textures/block/destroy_stage_2.png"],
            ["$textures/block/destroy_stage_3.png"],
            ["$textures/block/destroy_stage_4.png"],
            ["$textures/block/destroy_stage_5.png"],
            ["$textures/block/destroy_stage_6.png"],
            ["$textures/block/destroy_stage_7.png"],
            ["$textures/block/destroy_stage_8.png"],
            ["$textures/block/destroy_stage_9.png"],
            ["$textures/block/detector_rail.png"],
            ["$textures/block/detector_rail_on.png"],
            ["$textures/block/diamond_block.png"],
            ["$textures/block/diamond_ore.png"],
            ["$textures/block/diorite.png"],
            ["$textures/block/dirt.png"],
            ["$textures/block/dispenser_front.png"],
            ["$textures/block/dispenser_front_vertical.png"],
            ["$textures/block/dragon_egg.png"],
            ["$textures/block/dried_kelp_bottom.png"],
            ["$textures/block/dried_kelp_side.png"],
            ["$textures/block/dried_kelp_top.png"],
            ["$textures/block/dripstone_block.png"],
            ["$textures/block/dropper_front.png"],
            ["$textures/block/dropper_front_vertical.png"],
            ["$textures/block/emerald_block.png"],
            ["$textures/block/emerald_ore.png"],
            ["$textures/block/enchanting_table_bottom.png"],
            ["$textures/block/enchanting_table_side.png"],
            ["$textures/block/enchanting_table_top.png"],
            ["$textures/block/end_portal_frame_eye.png"],
            ["$textures/block/end_portal_frame_side.png"],
            ["$textures/block/end_portal_frame_top.png"],
            ["$textures/block/end_rod.png"],
            ["$textures/block/end_stone.png"],
            ["$textures/block/end_stone_bricks.png"],
            ["$textures/block/exposed_chiseled_copper.png"],
            ["$textures/block/exposed_copper.png"],
            ["$textures/block/exposed_copper_bulb.png"],
            ["$textures/block/exposed_copper_bulb_lit.png"],
            ["$textures/block/exposed_copper_bulb_lit_powered.png"],
            ["$textures/block/exposed_copper_bulb_powered.png"],
            ["$textures/block/exposed_copper_door_bottom.png"],
            ["$textures/block/exposed_copper_door_top.png"],
            ["$textures/block/exposed_copper_grate.png"],
            ["$textures/block/exposed_copper_trapdoor.png"],
            ["$textures/block/exposed_cut_copper.png"],
            ["$textures/block/farmland.png"],
            ["$textures/block/farmland_moist.png"],
            ["$textures/block/fern.png"],
            ["$textures/block/fire_0.png"],
            ["$textures/block/fire_0.png.mcmeta"],
            ["$textures/block/fire_1.png"],
            ["$textures/block/fire_1.png.mcmeta"],
            ["$textures/block/fire_coral.png"],
            ["$textures/block/fire_coral_block.png"],
            ["$textures/block/fire_coral_fan.png"],
            ["$textures/block/fletching_table_front.png"],
            ["$textures/block/fletching_table_side.png"],
            ["$textures/block/fletching_table_top.png"],
            ["$textures/block/flower_pot.png"],
            ["$textures/block/flowering_azalea_leaves.png"],
            ["$textures/block/flowering_azalea_side.png"],
            ["$textures/block/flowering_azalea_top.png"],
            ["$textures/block/frogspawn.png"],
            ["$textures/block/frosted_ice_0.png"],
            ["$textures/block/frosted_ice_1.png"],
            ["$textures/block/frosted_ice_2.png"],
            ["$textures/block/frosted_ice_3.png"],
            ["$textures/block/furnace_front.png"],
            ["$textures/block/furnace_front_on.png"],
            ["$textures/block/furnace_side.png"],
            ["$textures/block/furnace_top.png"],
            ["$textures/block/gilded_blackstone.png"],
            ["$textures/block/glass.png"],
            ["$textures/block/glass_pane_top.png"],
            ["$textures/block/glow_item_frame.png"],
            ["$textures/block/glow_lichen.png"],
            ["$textures/block/glowstone.png"],
            ["$textures/block/gold_block.png"],
            ["$textures/block/gold_ore.png"],
            ["$textures/block/granite.png"],
            ["$textures/block/grass.png"],
            ["$textures/block/grass_block_side.png"],
            ["$textures/block/grass_block_side_overlay.png"],
            ["$textures/block/grass_block_snow.png"],
            ["$textures/block/grass_block_top.png"],
            ["$textures/block/grass_path_side.png"],
            ["$textures/block/grass_path_top.png"],
        ])}
    </p></details>
`;
const guide_content = `
    ${banner}
    <h1>Local Oaf's 4&times;4 - Version ${version}</h1>
    <p>
        
    </p>
`;
const credits_content = `
    <h1>Local Oaf's 4&times;4 - Version ${version}</h1>
    <p>
        Software Used:<br>
        ${list2([
            ["<a href=\"https://www.minecraft.net/en-us/store/minecraft-deluxe-collection-pc?tabs=%7B%22MC_Tabs_0%22%3A0%7D\">Minecraft Java Edition</a>"],
            ["<a href=\"https://optifine.net/home\">OptiFine</a>"],
            ["<a href=\"https://www.mozilla.org/en-US/firefox/new/?redirect_source=firefox-com\">Mozilla Firefox</a>"],
            ["<a href=\"https://www.microsoft.com/en-us/edge/?form=MA13FJ\">MS Edge</a>"],
            ["<a href=\"https://microsoft-paint-3d.en.softonic.com/?ex=RAMP-2639.1\">MS Paint 3D</a>"],
            ["<a href=\"https://mh-nexus.de/en/hxd/\">HxD</a>"],
            ["<a href=\"https://code.visualstudio.com/\">Visual Studio Code (VSC)</a>"],
            ["<a href=\"https://chatgpt.com/\">ChatGPT</a>"],
            ["<a href=\"https://www.blender.org/\">Blender</a>"],
            ["<a href=\"https://www.blockbench.net/\">Blockbench</a>"]
        ])}
        <br>
        <br>
        <br>
        <br>
        Mozilla Firefox / MS Edge:<br>
        &emsp;&emsp;• HTML viewing<br>
        <br>
        MS Paint 3D:<br>
        &emsp;&emsp;• Texturing<br>
        <br>
        HxD:<br>
        &emsp;&emsp;• .bin file editing<br>
        <br>
        Visual Studio Code (VSC):<br>
        &emsp;&emsp;• Text file editing<br>
        <br>
        ChatGPT:<br>
        &emsp;&emsp;• Design for the "&" character in the ASCII table<br>
        <br>
        Blender:<br>
        &emsp;&emsp;• Block modelling (degisn only)<br>
        <br>
        Blockbench:<br>
        &emsp;&emsp;• Certain block / item models<br>
        &emsp;&emsp;• Entity models
    </p>
`;
window.onload = function(){
    try {
        document.getElementById("changelog_content").innerHTML = `${changelog_content}`;
    } catch {
        console.log("no element named changelog_content found, skipping...");
    };


    try {
        document.getElementById("guide_content").innerHTML = `${guide_content}`;
    } catch {
        console.log("no element named guide_content found, skipping...");
    };


    try{
        document.getElementById("credits_content").innerHTML = `${credits_content}`;
    } catch {
        console.log("no element named credits_content found, skipping...");
    };
};
