const current_version=`b1.0.1.0`;
const banner=`<img src="webassets/banner.png"class="banner"alt="If this banner doesn't render, your installation of the pack may be corrupted...<br>Try re-downloading the pack... If the problem persists it's likely a developer issue!" /`;
function list2(functionInput2){
    let temp=[""];
    for(var cur in functionInput2){
        let temp2=typeof(functionInput2[cur])
        if(temp2=="string"){
            temp.push(`• ${functionInput2[cur].toString()}<br>`);
        }else if(temp2=="object"){
            if(functionInput2[cur].length==1){
                temp.push(`&emsp;&emsp;• ${functionInput2[cur][0].toString()}<br>`);
            }else if(functionInput2[cur].length==2){
                temp.push(`${"&emsp;".repeat(functionInput2[cur][1])}• ${functionInput2[cur][0].toString()}<br>`);
            };
        };
    };
    temp.slice(1);
    return temp.join("");
};
const changelog_content=`
    ${banner}<br><br>
    <h1>Local Oaf's 4×4 - Version ${current_version}</h1>
    <details><summary><h2>b1.0.0.0 (June 2<sup>nd</sup>, 2025)</h2></summary><p>
        ${list2([
            "Added/Modified files:",
            ["%_changelog.html"],
            ["%_credits.html"],
            ["%_guide.html"],
            ["%pack.mcmeta"],
            ["%assets/minecraft/blockstates/attached_pumpkin_stem.json"],//defer to melon stem
            ["%assets/minecraft/blockstates/bamboo.json"],//eliminate age1
            ["%assets/minecraft/blockstates/pumpkin_stem.json"],//defer to melon stem
            ["%assets/minecraft/models/block/bamboo1_age0.json"],
            ["%assets/minecraft/models/block/bamboo2_age0.json"],
            ["%assets/minecraft/models/block/bamboo3_age0.json"],
            ["%assets/minecraft/models/block/bamboo4_age0.json"],
            ["%assets/minecraft/models/block/carpet.json"],
            ["%assets/minecraft/models/block/cartography_table.json"],
            ["%assets/minecraft/models/block/crafter.json"],
            ["%assets/minecraft/models/block/crafter_crafting.json"],
            ["%assets/minecraft/models/block/crafter_triggered.json"],
            ["%assets/minecraft/models/block/door_bottom_left.json"],
            ["%assets/minecraft/models/block/door_bottom_left_open.json"],
            ["%assets/minecraft/models/block/door_bottom_right.json"],
            ["%assets/minecraft/models/block/door_bottom_right_open.json"],
            ["%assets/minecraft/models/block/door_top_left.json"],
            ["%assets/minecraft/models/block/door_top_left_open.json"],
            ["%assets/minecraft/models/block/door_top_right.json"],
            ["%assets/minecraft/models/block/door_top_right_open.json"],
            ["%assets/minecraft/models/block/pointed_dripstone_down_base.json"],
            ["%assets/minecraft/models/block/pointed_dripstone_down_frustum.json"],
            ["%assets/minecraft/models/block/pointed_dripstone_down_middle.json"],
            ["%assets/minecraft/models/block/pointed_dripstone_down_tip.json"],
            ["%assets/minecraft/models/block/pointed_dripstone_down_tip_merge.json"],
            ["%assets/minecraft/models/block/pointed_dripstone_up_base.json"],
            ["%assets/minecraft/models/block/pointed_dripstone_up_frustum.json"],
            ["%assets/minecraft/models/block/pointed_dripstone_up_middle.json"],
            ["%assets/minecraft/models/block/pointed_dripstone_up_tip.json"],
            ["%assets/minecraft/models/block/pointed_dripstone_up_tip_merge.json"],
            ["%assets/minecraft/models/block/template_anvil.json"],
            ["%assets/minecraft/models/block/template_orientable_trapdoor_bottom.json"],
            ["%assets/minecraft/models/block/template_orientable_trapdoor_open.json"],
            ["%assets/minecraft/models/block/template_orientable_trapdoor_top.json"],
            ["%assets/minecraft/models/item/generated.bbmodel"],
            ["%assets/minecraft/models/item/generated.json"],
            ["%assets/minecraft/models/item/_oaf/generated_render.json"],
            ["%assets/minecraft/textures/block/acacia_door_bottom.png"],
            ["%assets/minecraft/textures/block/acacia_door_top.png"],
            ["%assets/minecraft/textures/block/acacia_leaves.png"],
            ["%assets/minecraft/textures/block/acacia_log.png"],
            ["%assets/minecraft/textures/block/acacia_log_top.png"],
            ["%assets/minecraft/textures/block/acacia_planks.png"],
            ["%assets/minecraft/textures/block/acacia_sapling.png"],
            ["%assets/minecraft/textures/block/acacia_trapdoor.png"],
            ["%assets/minecraft/textures/block/activator_rail.png"],
            ["%assets/minecraft/textures/block/activator_rail_on.png"],
            ["%assets/minecraft/textures/block/allium.png"],
            ["%assets/minecraft/textures/block/amethyst_block.png"],
            ["%assets/minecraft/textures/block/amethyst_cluster.png"],
            ["%assets/minecraft/textures/block/ancient_debris_side.png"],
            ["%assets/minecraft/textures/block/ancient_debris_top.png"],
            ["%assets/minecraft/textures/block/andesite.png"],
            ["%assets/minecraft/textures/block/anvil.png"],
            ["%assets/minecraft/textures/block/anvil_top.png"],
            ["%assets/minecraft/textures/block/attached_melon_stem.png"],
            ["%assets/minecraft/textures/block/azalea_leaves.png"],
            ["%assets/minecraft/textures/block/azalea_plant.png"],
            ["%assets/minecraft/textures/block/azalea_side.png"],
            ["%assets/minecraft/textures/block/azalea_top.png"],
            ["%assets/minecraft/textures/block/azure_bluet.png"],
            ["%assets/minecraft/textures/block/bamboo_block.png"],
            ["%assets/minecraft/textures/block/bamboo_block_top.png"],
            ["%assets/minecraft/textures/block/bamboo_door_bottom.png"],
            ["%assets/minecraft/textures/block/bamboo_door_top.png"],
            ["%assets/minecraft/textures/block/bamboo_fence_gate_particle.png"],
            ["%assets/minecraft/textures/block/bamboo_fence_particle.png"],
            ["%assets/minecraft/textures/block/bamboo_large_leaves.png"],
            ["%assets/minecraft/textures/block/bamboo_mosaic.png"],
            ["%assets/minecraft/textures/block/bamboo_planks.png"],
            ["%assets/minecraft/textures/block/bamboo_singleleaf.png"],
            ["%assets/minecraft/textures/block/bamboo_small_leaves.png"],
            ["%assets/minecraft/textures/block/bamboo_stage0.png"],
            ["%assets/minecraft/textures/block/bamboo_stalk.png"],
            ["%assets/minecraft/textures/block/bamboo_trapdoor.png"],
            ["%assets/minecraft/textures/block/barrel_bottom.png"],
            ["%assets/minecraft/textures/block/barrel_side.png"],
            ["%assets/minecraft/textures/block/barrel_top.png"],
            ["%assets/minecraft/textures/block/barrel_top_open.png"],
            ["%assets/minecraft/textures/block/basalt_side.png"],
            ["%assets/minecraft/textures/block/basalt_top.png"],
            ["%assets/minecraft/textures/block/beacon.png"],
            ["%assets/minecraft/textures/block/bedrock.png"],
            ["%assets/minecraft/textures/block/glass.png"],//appears so early because used by beacon
            ["%assets/minecraft/textures/block/obsidian.png"],//appears so early because used by beacon
            ["%assets/minecraft/textures/block/_oaf/bamboo_stalk_end.png"],
            ["%assets/minecraft/textures/block/_oaf/cartography_table.png"],
            ["%assets/minecraft/textures/block/_oaf/crafter.png"],
            ["%assets/minecraft/textures/block/_oaf/invisible.png"],//used by item/generated
            ["%assets/minecraft/textures/block/_oaf/pointed_dripstone.png"],
            ["%webassets/core.js"],
            ["%webassets/guide.css"],
            ["%webassets/mc.ttf"]
        ])}
    </p></details><br><details><summary><h2>b1.0.1.0 (June 7<sup>th</sup>, 2025)</h2></summary><p>
        ${list2([
            "Added/Modified files:",
            ["%assets/minecraft/blockstates/lava_cauldron.json"],
            ["%assets/minecraft/blockstates/powder_snow_cauldron.json"],
            ["%assets/minecraft/blockstates/water_cauldron.json"],
            ["%assets/minecraft/models/block/cake.json"],
            ["%assets/minecraft/models/block/cake_slice1.json"],
            ["%assets/minecraft/models/block/cake_slice2.json"],
            ["%assets/minecraft/models/block/cake_slice3.json"],
            ["%assets/minecraft/models/block/cake_slice4.json"],
            ["%assets/minecraft/models/block/cake_slice5.json"],
            ["%assets/minecraft/models/block/cake_slice6.json"],
            ["%assets/minecraft/models/block/campfire_off.json"],
            ["%assets/minecraft/models/block/cauldron.json"],
            ["%assets/minecraft/models/block/chorus_plant.json"],
            ["%assets/minecraft/models/block/chorus_plant_noside.json"],
            ["%assets/minecraft/models/block/chorus_plant_noside1.json"],
            ["%assets/minecraft/models/block/chorus_plant_noside2.json"],
            ["%assets/minecraft/models/block/chorus_plant_noside3.json"],
            ["%assets/minecraft/models/block/comparator.json"],
            ["%assets/minecraft/models/block/comparator_on.json"],
            ["%assets/minecraft/models/block/comparator_on_subtract.json"],
            ["%assets/minecraft/models/block/comparator_subtract.json"],
            ["%assets/minecraft/models/block/composter.json"],
            ["%assets/minecraft/models/block/composter_contents_ready.json"],
            ["%assets/minecraft/models/block/composter_contents1.json"],
            ["%assets/minecraft/models/block/composter_contents2.json"],
            ["%assets/minecraft/models/block/composter_contents3.json"],
            ["%assets/minecraft/models/block/composter_contents4.json"],
            ["%assets/minecraft/models/block/composter_contents5.json"],
            ["%assets/minecraft/models/block/composter_contents6.json"],
            ["%assets/minecraft/models/block/composter_contents7.json"],
            ["%assets/minecraft/models/block/redstone_torch.json"],
            ["%assets/minecraft/models/block/redstone_torch_off.json"],
            ["%assets/minecraft/models/block/redstone_wall_torch.json"],
            ["%assets/minecraft/models/block/redstone_wall_torch_off.json"],
            ["%assets/minecraft/models/block/template_campfire.json"],
            ["%assets/minecraft/models/block/template_chorus_flower.json"],
            ["%assets/minecraft/models/block/template_torch.json"],
            ["%assets/minecraft/models/block/template_torch_wall.json"],
            ["%assets/minecraft/optifine/textures/icons.png"],
            ["%assets/minecraft/textures/block/bee_nest_bottom.png"],
            ["%assets/minecraft/textures/block/bee_nest_front.png"],
            ["%assets/minecraft/textures/block/bee_nest_front_honey.png"],
            ["%assets/minecraft/textures/block/bee_nest_side.png"],
            ["%assets/minecraft/textures/block/bee_nest_top.png"],
            ["%assets/minecraft/textures/block/beehive_end.png"],
            ["%assets/minecraft/textures/block/beehive_front.png"],
            ["%assets/minecraft/textures/block/beehive_front_honey.png"],
            ["%assets/minecraft/textures/block/beehive_front_side.png"],
            ["%assets/minecraft/textures/block/beetroots_stage0.png"],
            ["%assets/minecraft/textures/block/beetroots_stage1.png"],
            ["%assets/minecraft/textures/block/beetroots_stage2.png"],
            ["%assets/minecraft/textures/block/beetroots_stage3.png"],
            ["%assets/minecraft/textures/block/bell_bottom.png"],
            ["%assets/minecraft/textures/block/bell_top.png"],
            ["%assets/minecraft/textures/block/big_dripleaf_side.png"],
            ["%assets/minecraft/textures/block/big_dripleaf_stem.png"],
            ["%assets/minecraft/textures/block/big_dripleaf_tip.png"],
            ["%assets/minecraft/textures/block/big_dripleaf_top.png"],
            ["%assets/minecraft/textures/block/birch_door_bottom.png"],
            ["%assets/minecraft/textures/block/birch_door_top.png"],
            ["%assets/minecraft/textures/block/birch_log.png"],
            ["%assets/minecraft/textures/block/birch_log_top.png"],
            ["%assets/minecraft/textures/block/birch_planks.png"],
            ["%assets/minecraft/textures/block/birch_trapdoor.png"],
            ["%assets/minecraft/textures/block/black_concrete.png"],
            ["%assets/minecraft/textures/block/black_concrete_powder.png"],
            ["%assets/minecraft/textures/block/black_glazed_terracotta.png"],
            ["%assets/minecraft/textures/block/black_shulker_box.png"],
            ["%assets/minecraft/textures/block/black_stained_glass.png"],
            ["%assets/minecraft/textures/block/black_terracotta.png"],
            ["%assets/minecraft/textures/block/black_wool.png"],
            ["%assets/minecraft/textures/block/blackstone.png"],
            ["%assets/minecraft/textures/block/blackstone_top.png"],
            ["%assets/minecraft/textures/block/blast_furnace_front.png"],
            ["%assets/minecraft/textures/block/blast_furnace_front_on.png"],
            ["%assets/minecraft/textures/block/blast_furnace_front_on.png.mcmeta"],
            ["%assets/minecraft/textures/block/blast_furnace_side.png"],
            ["%assets/minecraft/textures/block/blast_furnace_top.png"],
            ["%assets/minecraft/textures/block/blue_concrete.png"],
            ["%assets/minecraft/textures/block/blue_concrete_powder.png"],
            ["%assets/minecraft/textures/block/blue_glazed_terracotta.png"],
            ["%assets/minecraft/textures/block/blue_ice.png"],
            ["%assets/minecraft/textures/block/blue_shulker_box.png"],
            ["%assets/minecraft/textures/block/blue_stained_glass.png"],
            ["%assets/minecraft/textures/block/blue_terracotta.png"],
            ["%assets/minecraft/textures/block/blue_wool.png"],
            ["%assets/minecraft/textures/block/bone_block_side.png"],
            ["%assets/minecraft/textures/block/bone_block_top.png"],
            ["%assets/minecraft/textures/block/bookshelf.png"],
            ["%assets/minecraft/textures/block/brain_coral_block.png"],
            ["%assets/minecraft/textures/block/brewing_stand_base.png"],
            ["%assets/minecraft/textures/block/bricks.png"],
            ["%assets/minecraft/textures/block/brown_concrete.png"],
            ["%assets/minecraft/textures/block/brown_concrete_powder.png"],
            ["%assets/minecraft/textures/block/brown_glazed_terracotta.png"],
            ["%assets/minecraft/textures/block/brown_mushroom_block.png"],
            ["%assets/minecraft/textures/block/brown_shulker_box.png"],
            ["%assets/minecraft/textures/block/brown_stained_glass.png"],
            ["%assets/minecraft/textures/block/brown_terracotta.png"],
            ["%assets/minecraft/textures/block/brown_wool.png"],
            ["%assets/minecraft/textures/block/bubble_coral_block.png"],
            ["%assets/minecraft/textures/block/budding_amethyst.png"],
            ["%assets/minecraft/textures/block/cake_bottom.png"],
            ["%assets/minecraft/textures/block/cake_side.png"],
            ["%assets/minecraft/textures/block/cake_top.png"],
            ["%assets/minecraft/textures/block/calcite.png"],
            ["%assets/minecraft/textures/block/calibrated_sculk_sensor_top.png"],
            ["%assets/minecraft/textures/block/campfire_fire.png.mcmeta"],
            ["%assets/minecraft/textures/block/campfire_log.png"],
            ["%assets/minecraft/textures/block/campfire_log_lit.png"],
            ["%assets/minecraft/textures/block/campfire_log_lit.png.mcmeta"],
            ["%assets/minecraft/textures/block/carved_pumpkin.png"],
            ["%assets/minecraft/textures/block/cauldron_side.png"],
            ["%assets/minecraft/textures/block/chain_command_block_back.png"],
            ["%assets/minecraft/textures/block/chain_command_block_back.png.mcmeta"],
            ["%assets/minecraft/textures/block/chain_command_block_conditional.png"],
            ["%assets/minecraft/textures/block/chain_command_block_conditional.png.mcmeta"],
            ["%assets/minecraft/textures/block/chain_command_block_front.png"],
            ["%assets/minecraft/textures/block/chain_command_block_front.png.mcmeta"],
            ["%assets/minecraft/textures/block/chain_command_block_side.png"],
            ["%assets/minecraft/textures/block/chain_command_block_side.png.mcmeta"],
            ["%assets/minecraft/textures/block/cherry_door_bottom.png"],
            ["%assets/minecraft/textures/block/cherry_log.png"],
            ["%assets/minecraft/textures/block/cherry_log_top.png"],
            ["%assets/minecraft/textures/block/cherry_planks.png"],
            ["%assets/minecraft/textures/block/chiseled_bookshelf_empty.png"],
            ["%assets/minecraft/textures/block/chiseled_bookshelf_occupied.png"],
            ["%assets/minecraft/textures/block/chiseled_bookshelf_side.png"],
            ["%assets/minecraft/textures/block/chiseled_bookshelf_top.png"],
            ["%assets/minecraft/textures/block/chiseled_copper.png"],
            ["%assets/minecraft/textures/block/chiseled_deepslate.png"],
            ["%assets/minecraft/textures/block/chiseled_nether_bricks.png"],
            ["%assets/minecraft/textures/block/chiseled_polished_blackstone.png"],
            ["%assets/minecraft/textures/block/chiseled_quartz_block.png"],
            ["%assets/minecraft/textures/block/chiseled_quartz_block_top.png"],
            ["%assets/minecraft/textures/block/chiseled_red_sandstone.png"],
            ["%assets/minecraft/textures/block/chiseled_resin_bricks.png"],
            ["%assets/minecraft/textures/block/chiseled_sandstone.png"],
            ["%assets/minecraft/textures/block/chiseled_stone_bricks.png"],
            ["%assets/minecraft/textures/block/chiseled_tuff.png"],
            ["%assets/minecraft/textures/block/chiseled_tuff_bricks.png"],
            ["%assets/minecraft/textures/block/chiseled_tuff_bricks_top.png"],
            ["%assets/minecraft/textures/block/chiseled_tuff_top.png"],
            ["%assets/minecraft/textures/block/chorus_flower.png"],
            ["%assets/minecraft/textures/block/chorus_flower_dead.png"],
            ["%assets/minecraft/textures/block/chorus_plant.png"],
            ["%assets/minecraft/textures/block/clay.png"],
            ["%assets/minecraft/textures/block/coal_block.png"],
            ["%assets/minecraft/textures/block/coal_ore.png"],
            ["%assets/minecraft/textures/block/coarse_dirt.png"],
            ["%assets/minecraft/textures/block/cobbled_deepslate.png"],
            ["%assets/minecraft/textures/block/cobblestone.png"],
            ["%assets/minecraft/textures/block/command_block_back.png"],
            ["%assets/minecraft/textures/block/command_block_back.png.mcmeta"],
            ["%assets/minecraft/textures/block/command_block_conditional.png"],
            ["%assets/minecraft/textures/block/command_block_conditional.png.mcmeta"],
            ["%assets/minecraft/textures/block/command_block_front.png"],
            ["%assets/minecraft/textures/block/command_block_front.png.mcmeta"],
            ["%assets/minecraft/textures/block/command_block_side.png"],
            ["%assets/minecraft/textures/block/command_block_side.png.mcmeta"],
            ["%assets/minecraft/textures/block/comparator.png"],
            ["%assets/minecraft/textures/block/comparator_on.png"],
            ["%assets/minecraft/textures/block/composter_side.png"],
            ["%assets/minecraft/textures/block/crimson_stem.png.mcmeta"],
            ["%assets/minecraft/textures/block/fire_0.png.mcmeta"],
            ["%assets/minecraft/textures/block/fire_1.png.mcmeta"],
            ["%assets/minecraft/textures/block/kelp.png.mcmeta"],
            ["%assets/minecraft/textures/block/kelp_plant.png.mcmeta"],
            ["%assets/minecraft/textures/block/lava_flow.png.mcmeta"],
            ["%assets/minecraft/textures/block/lava_still.png.mcmeta"],
            ["%assets/minecraft/textures/block/lightning_rod_on.png"],
            ["%assets/minecraft/textures/block/magma.png.mcmeta"],
            ["%assets/minecraft/textures/block/nether_portal.png.mcmeta"],
            ["%assets/minecraft/textures/block/prismarine.png.mcmeta"],
            ["%assets/minecraft/textures/block/redstone_torch.png"],
            ["%assets/minecraft/textures/block/redstone_torch_off.png"],
            ["%assets/minecraft/textures/block/repeating_command_block_back.png.mcmeta"],
            ["%assets/minecraft/textures/block/repeating_command_block_conditional.png.mcmeta"],
            ["%assets/minecraft/textures/block/repeating_command_block_front.png.mcmeta"],
            ["%assets/minecraft/textures/block/repeating_command_block_side.png.mcmeta"],
            ["%assets/minecraft/textures/block/respawn_anchor_top.png.mcmeta"],
            ["%assets/minecraft/textures/block/sculk.png.mcmeta"],
            ["%assets/minecraft/textures/block/sculk_catalyst_side_bloom.png.mcmeta"],
            ["%assets/minecraft/textures/block/sculk_catalyst_top_bloom.png.mcmeta"],
            ["%assets/minecraft/textures/block/sculk_sensor_tendril_active.png.mcmeta"],
            ["%assets/minecraft/textures/block/sculk_sensor_tendril_inactive.png.mcmeta"],
            ["%assets/minecraft/textures/block/seagrass.png.mcmeta"],
            ["%assets/minecraft/textures/block/small_dripleaf_side.png"],
            ["%assets/minecraft/textures/block/smoker_front_on.png.mcmeta"],
            ["%assets/minecraft/textures/block/smooth_stone.png"],
            ["%assets/minecraft/textures/block/soul_campfire_fire.png.mcmeta"],
            ["%assets/minecraft/textures/block/soul_campfire_log_lit.png.mcmeta"],
            ["%assets/minecraft/textures/block/soul_fire_0.png.mcmeta"],
            ["%assets/minecraft/textures/block/soul_fire_1.png.mcmeta"],
            ["%assets/minecraft/textures/block/soul_torch.png"],
            ["%assets/minecraft/textures/block/stonecutter_saw.png.mcmeta"],
            ["%assets/minecraft/textures/block/tall_seagrass_bottom.png.mcmeta"],
            ["%assets/minecraft/textures/block/tall_seagrass_top.png.mcmeta"],
            ["%assets/minecraft/textures/block/torch.png"],
            ["%assets/minecraft/textures/block/warped_stem.png.mcmeta"],
            ["%assets/minecraft/textures/block/water_flow.png.mcmeta"],
            ["%assets/minecraft/textures/block/water_still.png.mcmeta"],
            ["%assets/minecraft/textures/effect/dither.png"],
            ["%assets/minecraft/textures/environment/end_sky.png"],
            ["%assets/minecraft/textures/environment/moon_phases.png"],
            ["%assets/minecraft/textures/environment/rain.png"],
            ["%assets/minecraft/textures/environment/snow.png"],
            ["%assets/minecraft/textures/environment/sun.png"],
            ["%assets/minecraft/textures/gui/accessibility.png"],
            ["%assets/minecraft/textures/gui/checkbox.png"],
            ["%assets/minecraft/textures/gui/info_icon.png"],
            ["%assets/minecraft/textures/gui/light_dirt_background.png"],
            ["%assets/minecraft/textures/gui/options_background.png"],
            ["%assets/minecraft/textures/gui/report_button.png"],
            ["%assets/minecraft/textures/gui/slider.png"],
            ["%assets/minecraft/textures/gui/presets/isles.png"],
            ["%assets/minecraft/textures/gui/realms/adventure.png"],
            ["%assets/minecraft/textures/gui/realms/empty_frame.png"],
            ["%assets/minecraft/textures/gui/realms/experience.png"],
            ["%assets/minecraft/textures/gui/realms/inspiration.png"],
            ["%assets/minecraft/textures/gui/realms/new_world.png"],
            ["%assets/minecraft/textures/gui/realms/no_realms.png"],
            ["%assets/minecraft/textures/gui/realms/snapshot_realms.png"],
            ["%assets/minecraft/textures/gui/realms/survival_spawn.png"],
            ["%assets/minecraft/textures/gui/realms/upload.png"],
            ["%assets/minecraft/textures/gui/title/edition.png"],
            ["%assets/minecraft/textures/gui/title/edition.png.mcmeta"],
            ["%assets/minecraft/textures/gui/title/minceraft.png"],
            ["%assets/minecraft/textures/gui/title/minceraft.png.mcmeta"],
            ["%assets/minecraft/textures/gui/title/minecraft.png"],
            ["%assets/minecraft/textures/gui/title/minecraft.png.mcmeta"],
            ["%assets/minecraft/textures/gui/title/mojangstudios.png"],
            ["%assets/minecraft/textures/gui/title/mojangstudios.png.mcmeta"],
            ["%assets/minecraft/textures/gui/title/realms.png"],
            ["%assets/minecraft/textures/gui/title/realms.png.mcmeta"],
            ["%assets/minecraft/textures/gui/title/background/panorama_0.png"],
            ["%assets/minecraft/textures/gui/title/background/panorama_1.png"],
            ["%assets/minecraft/textures/gui/title/background/panorama_2.png"],
            ["%assets/minecraft/textures/gui/title/background/panorama_3.png"],
            ["%assets/minecraft/textures/gui/title/background/panorama_4.png"],
            ["%assets/minecraft/textures/gui/title/background/panorama_5.png"],
            ["%assets/minecraft/textures/misc/credits_vignette.png"],
            ["%assets/minecraft/textures/misc/credits_vignette.png.mcmeta"],
            ["%assets/minecraft/textures/misc/enchanted_glint_entity.png"],
            ["%assets/minecraft/textures/misc/enchanted_glint_item.png"],
            ["%assets/minecraft/textures/misc/enchanted_glint_item.png.mcmeta"],
            ["%assets/minecraft/textures/misc/forcefield.png"],
            ["%assets/minecraft/textures/misc/nausea.png"],
            ["%assets/minecraft/textures/misc/nausea.png.mcmeta"],
            ["%assets/minecraft/textures/misc/powder_snow_outline.png"],
            ["%assets/minecraft/textures/misc/pumpkinblur.png"],
            ["%assets/minecraft/textures/misc/pumpkinblur.png.mcmeta"],
            ["%assets/minecraft/textures/misc/shadow.png"],
            ["%assets/minecraft/textures/misc/shadow.png.mcmeta"],
            ["%assets/minecraft/textures/misc/spyglass_scope.png"],
            ["%assets/minecraft/textures/misc/underwater.png"],
            ["%assets/minecraft/textures/misc/unknown_pack.png"],
            ["%assets/minecraft/textures/misc/unknown_server.png"],
            ["%assets/minecraft/textures/misc/vignette.png"],
            ["%assets/minecraft/textures/misc/vignette.png.mcmeta"],
            ["%assets/minecraft/textures/misc/alban.png"],
            ["%assets/minecraft/textures/misc/aztec.png"],
            ["%assets/minecraft/textures/misc/aztec2.png"],
            ["%assets/minecraft/textures/misc/back.png"],
            ["%assets/minecraft/textures/misc/backyard.png"],
            ["%assets/minecraft/textures/misc/baroque.png"],
            ["%assets/minecraft/textures/misc/bomb.png"],
            ["%assets/minecraft/textures/misc/bouquet.png"],
            ["%assets/minecraft/textures/misc/burning_skull.png"],
            ["%assets/minecraft/textures/misc/bust.png"],
            ["%assets/minecraft/textures/misc/cavebird.png"],
            ["%assets/minecraft/textures/misc/changing.png"],
            ["%assets/minecraft/textures/misc/cotan.png"],
            ["%assets/minecraft/textures/misc/courbet.png"],
            ["%assets/minecraft/textures/misc/creebet.png"],
            ["%assets/minecraft/textures/misc/donkey_kong.png"],
            ["%assets/minecraft/textures/misc/earth.png"],
            ["%assets/minecraft/textures/misc/endboss.png"],
            ["%assets/minecraft/textures/misc/fern.png"],
            ["%assets/minecraft/textures/misc/fighters.png"],
            ["%assets/minecraft/textures/misc/finding.png"],
            ["%assets/minecraft/textures/misc/fire.png"],
            ["%assets/minecraft/textures/misc/graham.png"],
            ["%assets/minecraft/textures/misc/humble.png"],
            ["%assets/minecraft/textures/misc/kebab.png"],
            ["%assets/minecraft/textures/misc/kz.png"],
            ["%assets/minecraft/textures/misc/lowmist.png"],
            ["%assets/minecraft/textures/misc/match.png"],
            ["%assets/minecraft/textures/misc/meditative.png"],
            ["%assets/minecraft/textures/misc/orb.png"],
            ["%assets/minecraft/textures/misc/owlemons.png"],
            ["%assets/minecraft/textures/misc/passage.png"],
            ["%assets/minecraft/textures/misc/pigscene.png"],
            ["%assets/minecraft/textures/misc/plant.png"],
            ["%assets/minecraft/textures/misc/pointer.png"],
            ["%assets/minecraft/textures/misc/pond.png"],
            ["%assets/minecraft/textures/misc/pool.png"],
            ["%assets/minecraft/textures/misc/prairie_ride.png"],
            ["%assets/minecraft/textures/misc/sea.png"],
            ["%assets/minecraft/textures/misc/skeleton.png"],
            ["%assets/minecraft/textures/misc/skull_and_roses.png"],
            ["%assets/minecraft/textures/misc/stage.png"],
            ["%assets/minecraft/textures/misc/sunflowers.png"],
            ["%assets/minecraft/textures/misc/sunset.png"],
            ["%assets/minecraft/textures/misc/tides.png"],
            ["%assets/minecraft/textures/misc/unpacked.png"],
            ["%assets/minecraft/textures/misc/void.png"],
            ["%assets/minecraft/textures/misc/wanderer.png"],
            ["%assets/minecraft/textures/misc/wasteland.png"],
            ["%assets/minecraft/textures/misc/water.png"],
            ["%assets/minecraft/textures/misc/wind.png"],
            ["%assets/minecraft/textures/misc/wither.png"]
        ])}
    </p></details>
`;
const guide_content=`
    ${banner}
    <h1>Local Oaf's 4×4 - Version ${current_version}</h1>
    <p>
        Please use OptiFine and have its settings set as follows:<br>
        <br>
        ${list2([
            ["Video Settings > Quality > Custom Entity Models : ON"],
            ["Video Settings > Quality > Custom Item Models : ON"]
        ])}
        <br>
        The latest version of OptiFine can be downloaded <a href = "https://optifine.net/downloads">here</a>.<br>
        The changelog can be viewed <a href = "_changelog.html#latest">here</a>.<br>
        The credits can be viewed <a href = "_credits.html#home">here</a>.<br>
        <br>
        <br>
        <span class = "smallText">
            This resource pack and its creator are in no way affiliated with 
            <a href="https://optifine.net/home/"class="greyLink">OptiFine</a>,
            <a href="https://www.microsoft.com/en-us/"class="greyLink">Microsoft®</a>, 
            <a href="https://www.minecraft.net/en-us/article/meet-mojang-studios/"class="greyLink">Mojang Studios™</a>, 
            <a href="https://www.minecraft.net/en-us/"class="greyLink">Minecraft®</a>, 
            <a href="https://www.curseforge.com/"class="greyLink">CurseForge®</a>, 
            or any employees/contractors of these organizations.
        </span>
    </p>
`;
const credits_content=`
    <h1>Local Oaf's 4×4 - Version ${current_version}</h1>
    <p>
        Software Used:<br>
        ${list2([
            ["<a href=\"https://www.minecraft.net/en-us/store/minecraft-deluxe-collection-pc?tabs=%7B%22MC_Tabs_0%22%3A0%7D\">Minecraft Java Edition</a>"],
            ["<a href=\"https://optifine.net/home\">OptiFine</a>"],
            ["<a href=\"https://www.mozilla.org/en-US/firefox/new/?redirect_source=firefox-com\">Mozilla Firefox</a>"],
            ["<a href=\"https://www.microsoft.com/en-us/edge/?form=MA13FJ\">MS Edge</a>"],
            ["<a href=\"https://microsoft-paint-3d.en.softonic.com/?ex=RAMP-2639.1\">MS Paint 3D</a>"],
            ["<a href=\"https://mh-nexus.de/en/hxd/\">HxD</a>"],
            ["<a href=\"https://code.visualstudio.com/\">Visual Studio Code (VSC)</a>"],
            ["<a href=\"https://chatgpt.com/\">ChatGPT</a>"],
            ["<a href=\"https://www.blender.org/\">Blender</a>"],
            ["<a href=\"https://www.blockbench.net/\">Blockbench</a>"]
        ])}
        <br>
        <br>
        <br>
        <br>
        Mozilla Firefox / MS Edge:<br>
        &emsp;&emsp;• HTML viewing<br>
        <br>
        MS Paint 3D:<br>
        &emsp;&emsp;• Texturing<br>
        <br>
        HxD:<br>
        &emsp;&emsp;• .bin file editing<br>
        <br>
        Visual Studio Code (VSC):<br>
        &emsp;&emsp;• Text file editing<br>
        <br>
        ChatGPT:<br>
        &emsp;&emsp;• Design for the "&" character in the ASCII table<br>
        <br>
        Blender:<br>
        &emsp;&emsp;• Block modelling (degisn only)<br>
        <br>
        Blockbench:<br>
        &emsp;&emsp;• Certain block / item models<br>
        &emsp;&emsp;• Entity models
    </p>
`;
window.onload=function(){
    try{document.getElementById("changelog_content").innerHTML=`${changelog_content}`;}catch{console.log("no element named changelog_content found, skipping...");};
    try{document.getElementById("guide_content").innerHTML=`${guide_content}`;}catch{console.log("no element named guide_content found, skipping...");};
    try{document.getElementById("credits_content").innerHTML=`${credits_content}`;}catch{console.log("no element named credits_content found, skipping...");};
};